/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddBankCreateRouteImport } from './routes/add-bank-create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MyTeamRouteImport } from './routes/my-team'
import { Route as OrderedRouteImport } from './routes/ordered'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TaskRouteImport } from './routes/task'
import { Route as VipRouteImport } from './routes/vip'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as ChangePasswordRouteImport } from './routes/change/password'
import { Route as TeamDetailsLevelRouteImport } from './routes/team-details.$level'
import { Route as PackageDetailsIdRouteImport } from './routes/package/details.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBankCreateRoute = AddBankCreateRouteImport.update({
  id: '/add-bank-create',
  path: '/add-bank-create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTeamRoute = MyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderedRoute = OrderedRouteImport.update({
  id: '/ordered',
  path: '/ordered',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskRoute = TaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change/password',
  path: '/change/password',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamDetailsLevelRoute = TeamDetailsLevelRouteImport.update({
  id: '/team-details/$level',
  path: '/team-details/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageDetailsIdRoute = PackageDetailsIdRouteImport.update({
  id: '/package/details/$id',
  path: '/package/details/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-bank-create': typeof AddBankCreateRoute
  '/auth': typeof AuthRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/my-team': typeof MyTeamRoute
  '/ordered': typeof OrderedRoute
  '/profile': typeof ProfileRoute
  '/task': typeof TaskRoute
  '/vip': typeof VipRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/change/password': typeof ChangePasswordRoute
  '/team-details/$level': typeof TeamDetailsLevelRoute
  '/package/details/$id': typeof PackageDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-bank-create': typeof AddBankCreateRoute
  '/auth': typeof AuthRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/my-team': typeof MyTeamRoute
  '/ordered': typeof OrderedRoute
  '/profile': typeof ProfileRoute
  '/task': typeof TaskRoute
  '/vip': typeof VipRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/change/password': typeof ChangePasswordRoute
  '/team-details/$level': typeof TeamDetailsLevelRoute
  '/package/details/$id': typeof PackageDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/add-bank-create': typeof AddBankCreateRoute
  '/auth': typeof AuthRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/my-team': typeof MyTeamRoute
  '/ordered': typeof OrderedRoute
  '/profile': typeof ProfileRoute
  '/task': typeof TaskRoute
  '/vip': typeof VipRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/change/password': typeof ChangePasswordRoute
  '/team-details/$level': typeof TeamDetailsLevelRoute
  '/package/details/$id': typeof PackageDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-bank-create'
    | '/auth'
    | '/exchange'
    | '/faq'
    | '/home'
    | '/my-team'
    | '/ordered'
    | '/profile'
    | '/task'
    | '/vip'
    | '/admin'
    | '/deposit'
    | '/history'
    | '/withdraw'
    | '/change/password'
    | '/team-details/$level'
    | '/package/details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-bank-create'
    | '/auth'
    | '/exchange'
    | '/faq'
    | '/home'
    | '/my-team'
    | '/ordered'
    | '/profile'
    | '/task'
    | '/vip'
    | '/admin'
    | '/deposit'
    | '/history'
    | '/withdraw'
    | '/change/password'
    | '/team-details/$level'
    | '/package/details/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/add-bank-create'
    | '/auth'
    | '/exchange'
    | '/faq'
    | '/home'
    | '/my-team'
    | '/ordered'
    | '/profile'
    | '/task'
    | '/vip'
    | '/_authenticated/admin'
    | '/_authenticated/deposit'
    | '/_authenticated/history'
    | '/_authenticated/withdraw'
    | '/change/password'
    | '/team-details/$level'
    | '/package/details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AddBankCreateRoute: typeof AddBankCreateRoute
  AuthRoute: typeof AuthRoute
  ExchangeRoute: typeof ExchangeRoute
  FaqRoute: typeof FaqRoute
  HomeRoute: typeof HomeRoute
  MyTeamRoute: typeof MyTeamRoute
  OrderedRoute: typeof OrderedRoute
  ProfileRoute: typeof ProfileRoute
  TaskRoute: typeof TaskRoute
  VipRoute: typeof VipRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  TeamDetailsLevelRoute: typeof TeamDetailsLevelRoute
  PackageDetailsIdRoute: typeof PackageDetailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-bank-create': {
      id: '/add-bank-create'
      path: '/add-bank-create'
      fullPath: '/add-bank-create'
      preLoaderRoute: typeof AddBankCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-team': {
      id: '/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof MyTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordered': {
      id: '/ordered'
      path: '/ordered'
      fullPath: '/ordered'
      preLoaderRoute: typeof OrderedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/change/password': {
      id: '/change/password'
      path: '/change/password'
      fullPath: '/change/password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-details/$level': {
      id: '/team-details/$level'
      path: '/team-details/$level'
      fullPath: '/team-details/$level'
      preLoaderRoute: typeof TeamDetailsLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/details/$id': {
      id: '/package/details/$id'
      path: '/package/details/$id'
      fullPath: '/package/details/$id'
      preLoaderRoute: typeof PackageDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AddBankCreateRoute: AddBankCreateRoute,
  AuthRoute: AuthRoute,
  ExchangeRoute: ExchangeRoute,
  FaqRoute: FaqRoute,
  HomeRoute: HomeRoute,
  MyTeamRoute: MyTeamRoute,
  OrderedRoute: OrderedRoute,
  ProfileRoute: ProfileRoute,
  TaskRoute: TaskRoute,
  VipRoute: VipRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  TeamDetailsLevelRoute: TeamDetailsLevelRoute,
  PackageDetailsIdRoute: PackageDetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
